// ==============================
// بيانات تجريبية للمشروع (Mock Data)
// استبدل هذه البيانات بـ API calls حقيقية عند ربط الـ Backend
// ==============================

export const mockHousings = [
  {
    id: 1,
    title: 'Al-Nuzha Apartment',
    city: 'Ramallah',
    area: 'Al-Nuzha',
    price: 200,
    rooms: 3,
    bathrooms: 1,
    wifi: true,
    parking: true,
    ac: true,
    furnished: true,
    image: 'https://picsum.photos/600/400?random=1',
    images: [
      'https://picsum.photos/600/400?random=1',
      'https://picsum.photos/600/400?random=11',
      'https://picsum.photos/600/400?random=21',
    ],
    description: 'Comfortable and modern apartment near Birzeit University. Fully furnished with all amenities including fast WiFi, parking, and 24/7 security.',
    owner: 'Khalid Owner',
    rating: 4.8,
    reviews: 24,
  },
  {
    id: 2,
    title: 'Student Villa',
    city: 'Nablus',
    area: 'Old City',
    price: 150,
    rooms: 2,
    bathrooms: 1,
    wifi: true,
    parking: false,
    ac: true,
    furnished: true,
    image: 'https://picsum.photos/600/400?random=2',
    images: [
      'https://picsum.photos/600/400?random=2',
      'https://picsum.photos/600/400?random=12',
      'https://picsum.photos/600/400?random=22',
    ],
    description: 'Modern housing near An-Najah University with great amenities and a friendly environment perfect for students.',
    owner: 'Khalid Owner',
    rating: 4.5,
    reviews: 18,
  },
  {
    id: 3,
    title: 'Budget Room',
    city: 'Hebron',
    area: 'City Center',
    price: 80,
    rooms: 1,
    bathrooms: 1,
    wifi: false,
    parking: false,
    ac: false,
    furnished: false,
    image: 'https://picsum.photos/600/400?random=3',
    images: [
      'https://picsum.photos/600/400?random=3',
      'https://picsum.photos/600/400?random=13',
    ],
    description: 'Affordable room for students on a budget. Located in the heart of Hebron city center.',
    owner: 'Khalid Owner',
    rating: 3.9,
    reviews: 7,
  },
  {
    id: 4,
    title: 'Luxury Suite',
    city: 'Ramallah',
    area: 'Al-Bireh',
    price: 350,
    rooms: 4,
    bathrooms: 2,
    wifi: true,
    parking: true,
    ac: true,
    furnished: true,
    image: 'https://picsum.photos/600/400?random=4',
    images: [
      'https://picsum.photos/600/400?random=4',
      'https://picsum.photos/600/400?random=14',
      'https://picsum.photos/600/400?random=24',
    ],
    description: 'Premium luxury housing with all amenities. Perfect for students who want comfort and style.',
    owner: 'Khalid Owner',
    rating: 5.0,
    reviews: 31,
  },
  {
    id: 5,
    title: 'Shared Apartment',
    city: 'Jenin',
    area: 'Downtown',
    price: 100,
    rooms: 2,
    bathrooms: 1,
    wifi: true,
    parking: false,
    ac: true,
    furnished: true,
    image: 'https://picsum.photos/600/400?random=5',
    images: [
      'https://picsum.photos/600/400?random=5',
      'https://picsum.photos/600/400?random=15',
    ],
    description: 'Shared housing with other students. Great for building friendships while studying.',
    owner: 'Khalid Owner',
    rating: 4.2,
    reviews: 12,
  },
  {
    id: 6,
    title: 'Studio Flat',
    city: 'Nablus',
    area: 'Rafidya',
    price: 120,
    rooms: 1,
    bathrooms: 1,
    wifi: true,
    parking: false,
    ac: true,
    furnished: true,
    image: 'https://picsum.photos/600/400?random=6',
    images: [
      'https://picsum.photos/600/400?random=6',
      'https://picsum.photos/600/400?random=16',
    ],
    description: 'Cozy studio flat near An-Najah University. Everything you need in one compact space.',
    owner: 'Khalid Owner',
    rating: 4.6,
    reviews: 19,
  },
]

export const mockBookings = [
  { id: 1, housingName: 'Al-Nuzha Apartment', city: 'Ramallah', roomType: 'Master Room', checkIn: '2024-03-01', checkOut: '2024-06-01', amount: 600, status: 'Confirmed', student: 'Ahmad Student' },
  { id: 2, housingName: 'Student Villa',      city: 'Nablus',   roomType: 'Single Room', checkIn: '2024-04-10', checkOut: '2024-07-10', amount: 450, status: 'Pending',   student: 'Sara Ali' },
  { id: 3, housingName: 'Studio Flat',        city: 'Nablus',   roomType: 'Double Room', checkIn: '2024-02-15', checkOut: '2024-05-15', amount: 360, status: 'Confirmed', student: 'Ahmad Student' },
  { id: 4, housingName: 'Budget Room',        city: 'Hebron',   roomType: 'Single Room', checkIn: '2024-01-01', checkOut: '2024-02-01', amount: 80,  status: 'Cancelled', student: 'Omar Hasan' },
]

export const mockPayments = [
  { id: 1, date: '2024-03-01', housing: 'Al-Nuzha Apartment', amount: 200, status: 'Paid',    method: 'Online' },
  { id: 2, date: '2024-04-01', housing: 'Al-Nuzha Apartment', amount: 200, status: 'Paid',    method: 'Online' },
  { id: 3, date: '2024-05-01', housing: 'Al-Nuzha Apartment', amount: 200, status: 'Pending', method: 'Cash' },
]

export const mockMaintenanceReports = [
  { id: 1, title: 'Water leak in bathroom', housing: 'Al-Nuzha Apartment', type: 'Plumbing',    status: 'Resolved',    date: '2024-03-10', student: 'Ahmad Student' },
  { id: 2, title: 'AC not working',         housing: 'Studio Flat',        type: 'Electrical',  status: 'In Progress', date: '2024-04-05', student: 'Ahmad Student' },
  { id: 3, title: 'WiFi very slow',         housing: 'Student Villa',      type: 'Network',     status: 'Open',        date: '2024-04-20', student: 'Sara Ali' },
]

export const mockUsers = [
  { id: 1, name: 'Admin User',    email: 'admin@dormify.com',   role: 'Admin',   status: 'Active', joined: '2023-01-15' },
  { id: 2, name: 'Ahmad Student', email: 'student@dormify.com', role: 'Student', status: 'Active', joined: '2023-09-01' },
  { id: 3, name: 'Khalid Owner',  email: 'owner@dormify.com',   role: 'Owner',   status: 'Active', joined: '2023-03-20' },
  { id: 4, name: 'Sara Ali',      email: 'sara@gmail.com',      role: 'Student', status: 'Active', joined: '2024-01-10' },
  { id: 5, name: 'Omar Hasan',    email: 'omar@gmail.com',      role: 'Student', status: 'Inactive', joined: '2023-11-05' },
]
